DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

INSERT INTO TB_HEROIS (NOME, PODER)
VALUES 
    ('Flash', 'Velô'),
    ('Aquaman', 'Nadadô'),
    ('Batman', 'Vuadô');

SELECT * FROM TB_HEROIS;

UPDATE TB_HEROIS
SET NOME = 'Goku', PODER = 'Lutadô'
WHERE ID = 1;

DELETE FROM TB_HEROIS WHERE ID=2;